// Queries defined outside the class
const queries = {
    handover: `
        SELECT iu.NAME, iu.NAME_LOCAL, iu.MOBILE_NUMBER, iu.EMAIL, eo.NAME_LOCAL
        FROM IPEMIS_PRODUCTION.OFFICER o
                 INNER JOIN IPEMIS_PRODUCTION.EDUCATION_OFFICE eo ON eo.EDUCATION_OFFICE_ID = o.POSTED_EDUCATION_OFFICE_ID
                 INNER JOIN IPEMIS_PRODUCTION.IEIMS_USER iu ON iu.IEIMS_USER_ID = o.OFFICER_ID
        WHERE POSTED_DESIGNATION_ID = 4250
          AND o.ROLE_TYPE = 'MAIN'
          AND iu.STATUS = 'ACTIVE'
          AND eo.UPAZILA_ID IN (
            SELECT s.UPAZILA_ID
            FROM IPEMIS_PRODUCTION.PEPMIS_ROOM_CONSTRUCTION_PLAN_SCHOOL_INFO prcpsi
                     INNER JOIN IPEMIS_PRODUCTION.SCHOOL s ON s.SCHOOL_ID = PRCPSI.SCHOOL_ID
            WHERE PRCPSI.STATUS = 'COMPLETED'
              AND PRCPSI.PEPMIS_ROOM_CONSTRUCTION_PLAN_ID = `,

    schoolcode: `
        SELECT s.SCHOOL_CODE FROM IPEMIS_PRODUCTION.PEPMIS_ROOM_CONSTRUCTION_PRIORITY_LIST prcpl
                                      INNER JOIN IPEMIS_PRODUCTION.SCHOOL s ON s.SCHOOL_ID = prcpl.SCHOOL_ID
        WHERE ROWNUM <= 3 AND prcpl.SCHOOL_ID NOT IN (
            SELECT  prcpsi.SCHOOL_ID FROM IPEMIS_PRODUCTION.PEPMIS_ROOM_CONSTRUCTION_PLAN_SCHOOL_INFO prcpsi
            WHERE PRCPSI.STATUS IN ('ORDER_GENERATED', 'UNDER_CONSTRUCTION', 'APPROVED', 'PENDING', 'DRAFT', 'COMPLETED', 'ON_REVIEW')
        )`,

    progressupdate: `
         SELECT iu.NAME , iu.NAME_LOCAL , iu.MOBILE_NUMBER , iu.EMAIL , eo.NAME_LOCAL
    FROM IPEMIS_PRODUCTION.OFFICER o
    INNER JOIN IPEMIS_PRODUCTION.EDUCATION_OFFICE eo ON eo.EDUCATION_OFFICE_ID = o.POSTED_EDUCATION_OFFICE_ID
    INNER JOIN IPEMIS_PRODUCTION.IEIMS_USER iu ON iu.IEIMS_USER_ID = o.OFFICER_ID
    WHERE POSTED_DESIGNATION_ID = 4250 AND o.ROLE_TYPE = 'MAIN' AND iu.STATUS = 'ACTIVE'
    AND eo.UPAZILA_ID IN
        (
            SELECT s.UPAZILA_ID
    FROM IPEMIS_PRODUCTION.PEPMIS_ROOM_CONSTRUCTION_PLAN_SCHOOL_INFO prcpsi
    INNER JOIN IPEMIS_PRODUCTION.SCHOOL s ON s.SCHOOL_ID = PRCPSI.SCHOOL_ID
    WHERE PRCPSI.STATUS ='ORDER_GENERATED' AND PRCPSI.PEPMIS_ROOM_CONSTRUCTION_PLAN_ID = `,

    planno: `SELECT * FROM IPEMIS_PRODUCTION.PEPMIS_ROOM_CONSTRUCTION_PLAN prcp WHERE STATUS = 'ORDER_GENERATED' 
ORDER BY PLAN_NO DESC `
};


export class sqlQuery {
    constructor() {}

    getSchoolCodeQuery() {
        return queries.schoolcode;
    }
    getPlanNo(){
        return queries.planno
    }
    getProgressUpdate(planNo){
        return queries.progressupdate+planNo+`)`;
    }
    getHandOverQuery(planNo) {
        return queries.handover+planNo+`)`;
    }
}
